### ISSUE TITLE
无法修改网站logo图标和收藏图标

### ISSUE THREAD

**Issue by RookieXv** [flysnow-org/maupassant-hugo#101]
<link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href='{{ "css/normalize.css" | relURL}}'>
    <link rel="stylesheet" href='{{ "css/style.css" | relURL }}'>

**Comment by rujews** [comment]
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

自己制作一个，放在static目录下,名字是favicon.ico
