### ISSUE TITLE
换到这个主题之后网站标签页上的那个小图标不显示了

### ISSUE THREAD

**Issue by KiteAB** [flysnow-org/maupassant-hugo#109]
如题

**Comment by rujews** [comment]
放个favicon.ico图标文件在static根目录下

**Comment by KiteAB** [comment]
没用

**Comment by KiteAB** [comment]
[~/D/b/static]── ─ ls
images  favicon.ico
[~/D/b/static]── ─ feh
[~/D/b/static]── ─ feh favicon.ico

**Comment by rujews** [comment]
多试下，然后在浏览器里方式访问下你这个图标，看提示什么

**Comment by KiteAB** [comment]
on ~/Documents/blog/static/favicon.ico  显示正常  可能我需要压缩一下分辨率？我现在的分辨率是297x295

**Comment by rujews** [comment]
网上有生成器的，Google一个，把你的图片传上去，自动生成最合适的给你。

**Comment by KiteAB** [comment]
Thx
