### ISSUE TITLE
关于文章归档页

### ISSUE THREAD

**Issue by xinghanting** [flysnow-org/maupassant-hugo#123]
想知道归档是什么意思？抱歉是第一次使用hugo。请问博客是放在post文件夹中还是放在content/tech文件夹中（我自己修改了identifier为tech）。设置type = identifier的作用是什么？

**Comment by rujews** [comment]
参考我的文档 [归档支持](https://github.com/flysnow-org/maupassant-hugo#%E6%96%87%E7%AB%A0%E5%BD%92%E6%A1%A3%E6%94%AF%E6%8C%81)
