### ISSUE TITLE
手机端看的时候有错位

### ISSUE THREAD

**Issue by pkptzx** [flysnow-org/maupassant-hugo#13]
您好,在手机端看的时候有错位。
比如标题 后面的 |  和分类名

还有在手机上觉得这个页尾的xxxxx power 这段话不好看了,中间折下行就好了.

祝好运.

**Comment by rujews** [comment]
嗯，是一个自动换行，因为手机宽度不一样，很难适应所有 @pkptzx

**Comment by to2false** [comment]
@rujews ![image](https://user-images.githubusercontent.com/21302817/49991100-f9845780-ffba-11e8-8c19-5c01f5227d50.png) safari桌面版和手机端都有这个问题
