### ISSUE TITLE
手机端-每篇文章的访问量统计有误？

### ISSUE THREAD

**Issue by ForrestSu** [flysnow-org/maupassant-hugo#133]
测试效果，每篇文章用的一个计数
测试平台：iPhone chrome/ Safari

**Comment by rujews** [comment]
用的不算子，按说没有太大问题

**Comment by ForrestSu** [comment]
> 用的不算子，按说没有太大问题

我这边 浏览了对比了下：

**PC 端效果：**
![image](https://user-images.githubusercontent.com/5516080/117636274-3a482100-b1b3-11eb-8682-8946ecb88ce4.png)

**手机端效果：**
![image](https://user-images.githubusercontent.com/5516080/117636497-72e7fa80-b1b3-11eb-8660-b5163d0ae275.png)

**Comment by rujews** [comment]
这么吊，看来不算子出问题了，最近我经常刷新不出来阅读数
