### ISSUE TITLE
[问题]新建菜单，菜单下如何挂载文章

### ISSUE THREAD

**Issue by randcoo** [flysnow-org/maupassant-hugo#142]
1. 新建了一个菜单
```yaml
[menu]
  [[menu.main]]
    identifier = "book"
    name = "读书"
    url = "/book/"
    weight = 2
```
2. 在该菜单下新建了文件
![image](https://user-images.githubusercontent.com/91318488/148485466-597b3528-0e86-48b0-a02e-51922fe0e9f5.png)

3. 点击菜单无法显示该菜单下的文章，难道只能放到里`post`目录中然后链接过去吗？
![image](https://user-images.githubusercontent.com/91318488/148485513-d18747d9-ef1a-4041-aef0-fc9a9c9bb048.png)
![image](https://user-images.githubusercontent.com/91318488/148485534-5263b2a0-7978-4fbc-9dd8-b4e1d5ab7e24.png)

**Comment by AhianZhang** [comment]
要想挂载多个文章，需要把 index.md 删掉或者重命名

**Comment by randcoo** [comment]
> 要想挂载多个文章，需要把 index.md 删掉或者重命名

完美解决 👍
