### ISSUE TITLE
老大你好，看文档说支持插入视频

### ISSUE THREAD

**Issue by vbskycn** [flysnow-org/maupassant-hugo#155]
老大你好，不知道怎么正确插入各种视频链接，能指点一下吗？文档里面没有详细说明
比如插入mp4  mp3
Youku bilibili
之类的
看模版里面好像有，但不知道怎么掉用
各位大佬有会的指点一下插入姿势

**Comment by rujews** [comment]
搜索下 Hugo shortcodes 相关知识
