### ISSUE TITLE
问题反馈：代码块不支持自动换行，溢出正文区域？

### ISSUE THREAD

**Issue by ForrestSu** [flysnow-org/maupassant-hugo#169]
- 问题描述：  如果单行代码过长，代码块不会auto-warp，从而遮盖右侧标签区域。
- 复现方式：查看作者的 [这篇文章](https://www.flysnow.org/2022/04/11/golang-workspace)， 减小浏览器宽度，即可复现。
- 效果图：
<img width="512px" alt="image" src="https://github.com/flysnow-org/maupassant-hugo/assets/5516080/dda85b57-13a9-4a8c-9b10-0d28a8dd4ddb">

**Comment by YuanJ2003** [comment]
解决了吗？我也遇到同样的问题
