### ISSUE TITLE
功能需求：置顶（Pin top）/文章间分隔/全站访客量

### ISSUE THREAD

**Issue by github-young** [flysnow-org/maupassant-hugo#42]
1. 请问能否加上置顶选项？

   背景：我是从hexo的Next.Gemini迁移过来的，原来在front matter里写
   ``` top: true ```
   即可使某篇post置顶。而这里我试了，并不行。
   ![Screenshot_2019-04-14-21-37-18-886_com yandex browser](https://user-images.githubusercontent.com/19162282/56093629-a46f3880-5efd-11e9-8369-75d66e7d45d3.png)

2. 能否使首页文章之间有较为明确的分隔标记？可以是像上图那样一篇文章一个框，也可以是简单的一条线 `` <br /> ``分隔。

3. 现在的 `` busuanzi `` 访问量统计是单篇文章的(page uv)，能不能在页面底部加一个全站访客/访问量统计(site pv/uv)？就像Next主题支持的那样。

最后很感谢您的repo！

**Comment by github-young** [comment]
自己现学了几天html，第3个“全站访客量”已经解决了，第2个分隔标记也快解决了，所以这两个需求不需要了

**Comment by accfcx** [comment]
我也说个需求：添加赞赏功能

**Comment by FeiChaoyu** [comment]
> 自己现学了几天html，第3个“全站访客量”已经解决了，第2个分隔标记也快解决了，所以这两个需求不需要了

怎么添加全站访问

**Comment by github-young** [comment]
> > 自己现学了几天html，第3个“全站访客量”已经解决了，第2个分隔标记也快解决了，所以这两个需求不需要了
> 
> 怎么添加全站访问

在footer（大概是这个名字）里面按照已有的加一项site uv的span，内容可以按busuanzi的说明

**Comment by FeiChaoyu** [comment]
请问你的搜索可以用吗

**Comment by github-young** [comment]
> 请问你的搜索可以用吗

搜索是谷歌的，你要挂梯子，不然自己换成bing或者baidu

**Comment by github-young** [comment]
置顶看来难搞，手动改日期实现吧；其它两个解决了，关了

**Comment by sanbeichahegongheguo** [comment]
全站访问量你咋做的？

**Comment by github-young** [comment]
> 
> 
> 全站访问量你咋做的？

加了个busuanzi计数器，不过我看现在这个好像已经自带了

**Comment by rujews** [comment]
busuanzi目前内置的是单篇文章的访问量统计，全站的还没有加

**Comment by github-young** [comment]
> 
> 
> 全站访问量你咋做的？

我修改了这个文件中的"busuanzi"那一段，你可以和原作者的对比一下
