### ISSUE TITLE
commit（bd965dda ）导致about页面显示在主页的文章列表中

### ISSUE THREAD

**Issue by skydamon** [flysnow-org/maupassant-hugo#45]
最近一次commit（bd965dda ）会导about页面被作为普通文章展示在主页。<www.flysnow.org>网站翻到第15页可以看见这个<https://www.flysnow.org/page/15/>  。我这边测试了一下。回退到上一个commit不会出现这个问题。

**Comment by LazyBonesLZ** [comment]
不只是about页面，最新版本还会在主页显示archives.md

**Comment by LazyBonesLZ** [comment]
> 最近一次commit（bd965dda ）会导about页面被作为普通文章展示在主页。<www.flysnow.org>网站翻到第15页可以看见这个https://www.flysnow.org/page/15/ 。我这边测试了一下。回退到上一个commit不会出现这个问题。

不懂js,不懂golang --！，我参照archives的single.html，照葫芦画瓢，把index.html修改了一下，这样首页就不再显示“post”或“posts"目录下的文档了：

`{{ partial "head" . }}

<body>
{{ partial "header" . }}

<div id="body">
    <div class="container">
        <div class="col-group">

            <div class="col-8" id="main">
                <div class="res-cons">
                   
                     {{ range (where (where .Site.Pages "Type" "in" (slice "post" "posts")) "Kind" "page").GroupByDate "2006" }}
                      {{ range .Pages }}
                        <article class="post">
                            <header>
                                <h1 class="post-title">
                                    <a href="{{ .Permalink }}" title="{{ .Title }}" >{{ .Title }}</a>
                                </h1>
                            </header>
                            <date class="post-meta meta-date">
                                {{ .Date.Year }}年{{ printf "%d" .Date.Month }}月{{ .Date.Day }}日
                            </date>
                            {{ with .Params.Categories }}
                            <div class="post-meta">
                                <span>|</span>
                                {{ range . }}
                                <span class="meta-category"><a href="{{ "/categories/" | absLangURL }}{{ . | urlize }}">{{ . }}</a></span>
                                {{ end }}
                            </div>
                            {{ end }}
                            <div class="post-content">
                                {{ .Summary }}……
                            </div>
                            <p class="readmore"><a href="{{ .Permalink }}">阅读全文</a></p>
                        </article>
                    {{ end }}
                    {{ end }}
                    {{ partial "paginator" . }}
                </div>
            </div>

            {{ partial "sidebar" . }}
        </div>
    </div>
</div>
{{ partial "footer" . }}

</body>
</html>
`

**Comment by rujews** [comment]
的确是的，我把他们都当成一个Page。Hugo本身的分页支持也是这么定的，如果我们过滤掉部分文章类型的，分页会不准确。我也参考了也写Hugo Theme ,他们也没有做区分。

**Comment by LazyBonesLZ** [comment]
是的。我修改了之后发现首页不能分页了。

**Comment by rujews** [comment]
我这里识别不了`Paginate `，这个函数还是什么，有对应的文档吗？
`{{ partial "paginator" . }}`这里也要同步改吧？
@LazyBonesLZ

**Comment by njudii** [comment]
还是单独一个about栏好看啊...这样设置多难受

**Comment by rujews** [comment]
> 还是单独一个about栏好看啊...这样设置多难受

单独一栏的也是支持的，不影响，你看我的博客。

**Comment by njudii** [comment]
> > 还是单独一个about栏好看啊...这样设置多难受
> 
> 单独一栏的也是支持的，不影响，你看我的博客。

嗯我知道的，我现在用的是几周前clone的，没问题。但是经过这次commit之后的，除了像楼上那样手动修改，还有什么简便的设置可以切换about是否单独显示吗？

**Comment by njudii** [comment]
好的，谢谢

**Comment by LazyBonesLZ** [comment]
> 我这里识别不了`Paginate `，这个函数还是什么，有对应的文档吗？
> `{{ partial "paginator" . }}`这里也要同步改吧？
> @LazyBonesLZ

额 ， 我本地hugo version：v0.55.3，会不会因为你的版本问题导致不识别？

**Comment by rujews** [comment]
我看官方给的，很早就有这一个了，但是我没查到`Paginate `是函数，还是变量，文档里没找到。
我的版本是0.54,也是很新了，编译的时候提示没这个

**Comment by LazyBonesLZ** [comment]
呃。。看看是不是这个呢？[https://gohugo.io/templates/pagination/#configure-pagination](https://gohugo.io/templates/pagination/#configure-pagination)

**Comment by rujews** [comment]
我看的和你的一样，我也想通过`.Paginate`，也就是文档里的这句`{{ $paginator := .Paginate (where .Pages "Type" "posts") }}`  但是报错，尴尬， @LazyBonesLZ

**Comment by LazyBonesLZ** [comment]
其实我只改了原来index.html一行代码
```
{{ range $index,$data := .Paginator.Pages }}
```
to

```
{{ range (.Paginate (where .Data.Pages "Section" "post")).Pages }}
```
测试发布时候，只是有一个warning，我不懂go语言,也就没管了。我试过把上面的参数"Section"改成"Type",也是同样的警告。
```
$ hugo server -D
Building sites … WARN 2019/05/06 18:30:06 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

**Comment by stu2162583** [comment]
也是遇到这样的问题。
比如 “关于” 菜单自定义，里面的about可能出现在首页，那么可以使用 `hugo new about/_index.md `，其他的菜单也是类似可以试试是否有问题

**Comment by fandean** [comment]
### 解决方法
在该文档的 Front Matter 中添加：
```
headless: true
```
我的about文件路径为： content/about/index.md

Hugo版本：v0.59.0

**Comment by cconecode** [comment]
> 其实我只改了原来index.html一行代码
> 
> ```
> {{ range $index,$data := .Paginator.Pages }}
> ```
> 
> to
> 
> ```
> {{ range (.Paginate (where .Data.Pages "Section" "post")).Pages }}
> ```
> 
> 测试发布时候，只是有一个warning，我不懂go语言,也就没管了。我试过把上面的参数"Section"改成"Type",也是同样的警告。
> 
> ```
> $ hugo server -D
> Building sites … WARN 2019/05/06 18:30:06 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> ```

根据你这个修改，首页变成空白页了

**Comment by cconecode** [comment]
> 也是遇到这样的问题。
> 比如 “关于” 菜单自定义，里面的about可能出现在首页，那么可以使用 `hugo new about/_index.md `，其他的菜单也是类似可以试试是否有问题
> 
> 抱歉，上面办法不太好使，一开始 `hugo server -D` 可能是缓存或者别的什么导致我这样可以，但是后来导出了就不行了，一片空白，各种issue翻阅，最后找到一种可行的设置
> 
> 主题目录下的 index.html就是首页，代码
> 
> ```
>  <div class="col-8" id="main">
>                 <div class="res-cons">
> 		    
>                     {{  $paginator := .Paginate (where .Site.Pages "Type" "posts") }}
>                     {{ range $index,$data := $paginator.Pages }}
> 
>                         <article class="post">
>                             <header>
>                                 <h1 class="post-title">
>                                     <a href="{{ .Permalink }}" title="{{ .Title }}" >{{ .Title }}</a>
>                                 </h1>
>                             </header>
> ```
> 
> 还没完。
> 另外就是可能出现posts空白文章，那么就在 posts下新建 _index.md
> 
> ```
> ---
> type: "index"
> daft: true
> ---
> ```
> 
> 导出的时候不要使用 -D

这个方法可以，不过要在文章里面设置 type 为 post
