### ISSUE TITLE
需求：可以通过content子目录的方式灵活增加/修改/删除文章类型

### ISSUE THREAD

**Issue by skydamon** [flysnow-org/maupassant-hugo#46]
和 Issue #45 关联的一个想法。

commit（bd965dda）更新后，文章类型不再必须是post和posts。通过在content目录下添加子目可以增加新的content type（一个子目录自动对应一个content type），这个和hugo的default behavior是一致的。

检索了一下代码，现在还有layouts/archives/single.html 和 layouts/partials/recent_post.html在代码中指定了文章类型，我觉得这个在灵活性方面不太友好。这个可以改成和hugo的default behavior一致吗？

**Comment by rujews** [comment]
是的，我自从放开了Post、Posts的限定后，就考虑如何更灵活的新增文章类型的方式，目前还不成熟，我再想想。
