### ISSUE TITLE
如何去掉文章详情url 最后的杠呢？

### ISSUE THREAD

**Issue by renyineng** [flysnow-org/maupassant-hugo#57]
http://xxx.com/2019/09/python.html/
文章后面总是自动多了个一个/,如何能去掉呢？

**Comment by github-young** [comment]
正常情况下是不应该有 .html的，像 `` https://username.github.io/xxx/python/ ``

**Comment by neo0moriarty** [comment]
使用slug配置url

**Comment by 82kg** [comment]
> 使用slug配置url

能否详细说下，或贴出配置呢

**Comment by 82kg** [comment]
set uglyurls = true  in your site’s config.toml

**Comment by renyineng** [comment]
resolved thanks

**Comment by qinchende** [comment]
https://github.com/gohugoio/hugoDocs/commit/ac2c4a4871e90ddfb180f23704ce7ec9023529ca

新版不再支持这个参数，运行前需要先设置系统的环境变量：

# env HUGO_UGLYURLS="true" hugo server -D
或
# env HUGO_UGLYURLS="true" hugo -D
