### ISSUE TITLE
[需求] 图片点击放大

### ISSUE THREAD

**Issue by ForrestSu** [flysnow-org/maupassant-hugo#65]
麻烦问下：实现点击图片时，图片放大的效果？这个好不好做，能不能提供点思路
添加 类似于 腾讯云专栏 [这篇博客](https://cloud.tencent.com/developer/article/1536291)

**Comment by CorPython** [comment]
@ForrestSu 欢迎参考我的实现方法,我是用了fancybox来实现https://corpython.github.io/post/%E6%B5%8B%E8%AF%95fancybox%E5%8A%9F%E8%83%BD/

**Comment by luodaoyi** [comment]
我提交了一个pr 合并就有了 参考楼上的方法改的 直接集成到模板了
