### ISSUE TITLE
左侧悬浮目录，一旦目录多了，下面就无法显示了

### ISSUE THREAD

**Issue by FeiChaoyu** [flysnow-org/maupassant-hugo#68]
如题

**Comment by rujews** [comment]
能贴个图吗？ @FeiChaoyu

**Comment by FeiChaoyu** [comment]
![image](https://user-images.githubusercontent.com/42114893/70108655-c8e27580-1684-11ea-9aca-67dfa19d2bdb.png)

**Comment by rujews** [comment]
哦，超过一屏了。~ @FeiChaoyu

**Comment by CorPython** [comment]
加1
