### ISSUE TITLE
不支持in-line code吗？

### ISSUE THREAD

**Issue by github-young** [flysnow-org/maupassant-hugo#77]
我发现没有渲染用 \`` \`` 包裹的 `` code `` 诶。

如图：

![图片](https://user-images.githubusercontent.com/19162282/71554552-a2cdac80-2a5b-11ea-868d-9baa66c77f25.png)

这是对应的md文本，我换了好几种写法都不行：

![图片](https://user-images.githubusercontent.com/19162282/71554571-cd1f6a00-2a5b-11ea-9192-31b8a5d4defa.png)

**Comment by rujews** [comment]
使用一个\`,不要使用三个。类似于这样`内部代码`

**Comment by github-young** [comment]
> 使用一个`,不要使用三个。类似于这样`内部代码`

可是你看我截图里1个\`也没有用的，那个 -

**Comment by github-young** [comment]
> 使用一个`,不要使用三个。类似于这样`内部代码`

我刚刚又测试了，用1个 `` ` `` 还是没用的

**Comment by rujews** [comment]
知道了，代码没问题，样式有点问题。我抽时间改下  @github-young

**Comment by rujews** [comment]
已修复，使用的类似github的样式 @github-young

**Comment by github-young** [comment]
> 已修复，使用的类似github的样式 @github-young

您好，我之前没细看，（今天才）发现修复后在列表环境里又不显示了，就像下图：

![图片](https://user-images.githubusercontent.com/19162282/71734915-01de5780-2e88-11ea-94fa-8a21bd379b08.png)

图中的 `` fig `` 也是用\``包裹的，但是没用渲染成代码环境。

预览地址：<https://github-young.github.io/maupassant-hugo/post/readme/>

谢谢您的主题！

**Comment by github-young** [comment]
我发现了，应该是把css里的 `` code `` 部分也照抄 `` p code `` 的内容就好了
