### ISSUE TITLE
有一个bug希望飞雪大佬帮我看一下

### ISSUE THREAD

**Issue by mxylovezh** [flysnow-org/maupassant-hugo#78]
你好飞雪，我用了你的博客主题功能非常强大，但是有一个bug，在工具和关于打开后左边都有一个fixed 的文章
![image](https://user-images.githubusercontent.com/50546350/71557016-129f5f80-2a7b-11ea-9161-66b37b93e9d2.png)
![image](https://user-images.githubusercontent.com/50546350/71557022-2e0a6a80-2a7b-11ea-9469-2cee28d193ca.png)
[博客链接](mengxiangyu.xyz)

**Comment by rujews** [comment]
文章目录，你这个是因为你的屏幕太窄了。如果不愿意使用的话，可以在文件头FM配置里把`toc=true`去掉  @mxylovezh

**Comment by mxylovezh** [comment]
好的，那我关了吧，谢谢大佬
