### ISSUE TITLE
[疑问]为什么一定要使用 post目录?

### ISSUE THREAD

**Issue by ForrestSu** [flysnow-org/maupassant-hugo#79]
>一定要使用post目录，而不是posts,一定要记住

麻烦问下，为什么一定要使用 post目录？

**Comment by rujews** [comment]
这个主题开始的约定

**Comment by Funnyang** [comment]
同样的疑问，目前没有使用 post 目录，似乎没有什么不同，是否可以解答一下呢？有什么区别
