### ISSUE TITLE
post下明明有多篇文章，为什么页面只显示一篇？

### ISSUE THREAD

**Issue by b3601993** [flysnow-org/maupassant-hugo#83]
-rw-r--r--@ 1 yutao  staff   1067  1  9 17:54 Gitee和GitHub对比.md
-rw-r--r--@ 1 yutao  staff    819  1  9 17:54 Gitee博客搭建.md
-rw-r--r--@ 1 yutao  staff    550  1  9 17:54 MacBook Pro 卸载node.md
-rw-r--r--@ 1 yutao  staff   2006  1  9 17:59 fatal: refusing to merge unrelated histories.md
-rw-r--r--@ 1 yutao  staff   7541  1  9 17:54 hugo部署到gitee pages.md
-rw-r--r--@ 1 yutao  staff  10123  1  9 17:40 虚拟机中的CentOS 7设置固定IP连接最理想的配置.md

上面是/myhugoblog/content/post 路径，可是只生成出来一篇文章，也就是最后一篇，好奇怪啊，大佬看到帮忙解答下

**Comment by b3601993** [comment]
原因找到了 是时间date造成的。
我很多文章都反正CSDN上面，那种文章是没有
---
title: "hugo部署到gitee pages"
date: 2020-01-03T18:39:07+08:00
---
类似上面的这样的标题的，我那300多篇文章，总不能手动一一添加吧。这也太坑了，
当初因为这个放弃hexo,难道我又要放弃Hugo？？？
难受~

**Comment by rujews** [comment]
哈哈，这个必然的，一篇文章总要必备标题和日期的 @b3601993
