### ISSUE TITLE
新版本的hugo不支持html语法?

### ISSUE THREAD

**Issue by CorPython** [flysnow-org/maupassant-hugo#84]
为什么我在文章用<span style="color:red"></span>给字体加上颜色,在博客上没有显示出来

**Comment by jdhao** [comment]
这是因为新版本的 Hugo （从 version 0.6）使用的 Markdown 渲染器从 blackfriday 改成了 goldmark，默认禁止在 Markdown 中使用 raw html 代码，不过可以自己手动开启相关选项，具体参见 [这里](https://jdhao.github.io/2019/12/29/hugo_html_not_shown/).

**Comment by CorPython** [comment]
@jdhao 非常感谢,已解决

**Comment by CorPython** [comment]
@rujews 还有一个疑问就是更新了之后原来的代码块复制功能好像又没了
