### ISSUE TITLE
显示代码行数的时候似乎有问题？会不对齐。

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [flysnow-org/maupassant-hugo#86]
![image](https://user-images.githubusercontent.com/32977199/74878264-f09ecb00-53a1-11ea-9a23-e704687afaa9.png)

如图。显示代码的行数的行间距要比代码短。
这是我的问题，还是主题的问题？

**Comment by Ben2277** [comment]
我也有这个问题

**Comment by rujews** [comment]
你这个是早期的主题版本？有没有更新到我这个最新版？

**Comment by Ben2277** [comment]
我这里是代码第一行会整体往右偏，从第二行开始能对齐，版本的话，昨天刚clone

**Comment by rujews** [comment]
是否自定义了markup？使用默认的试试。你看下我的博客 [https://www.flysnow.org/](https://www.flysnow.org/)

**Comment by Ben2277** [comment]
@rujews 注释所有markup设置后问题依然存在
![KnockPic_20200925173837](https://user-images.githubusercontent.com/41995412/94252074-0686f680-ff56-11ea-83fa-948f10d6590c.png)


相关的html代码：
```html
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell"><span style="color:#75715e"># yum install -y git</span>
<span style="color:#75715e"># cd /usr/local/site/xxx_blog/themes</span>
<span style="color:#75715e"># git clone https://github.com/flysnow-org/maupassant-hugo.git</span>
</code></pre></div>
```

**Comment by rujews** [comment]
还没遇到过，更新下Hugo版本呢？

**Comment by HC-miss** [comment]
我check了一下 具体原因是因为 行号和具体的代码行的`display`格式不统一的问题，我采用的是0.90的`hugo`， 生成的代码行`span`标签的`display`为`flex`， 而行号是`inline`， 由于一个是具体height一个是auto height， 所以就会导致对不齐， 我解决的方式是将`.post-content code`的css改写成
```css
.post-content code{
    display:flex;
    flex-direction: column;
}
```

**Comment by amesy** [comment]
@HC-miss   我使用的hugo版本是hugo v0.101.0， 现在遇到的情况是 line number 会溢出，改了 `.post-content code`也没生效，是不是还要改其他地方呢？

**Comment by amesy** [comment]
害，就是hugo版本的问题。刚下了个`v0.92.2`的，验证代码行数OK了。

**Comment by HC-miss** [comment]
> 害，就是hugo版本的问题。刚下了个`v0.92.2`的，验证代码行数OK了。

解决了就好 :satisfied:
