### ISSUE TITLE
请问代码复制功能应该怎么弄

### ISSUE THREAD

**Issue by hdtopku** [flysnow-org/maupassant-hugo#91]
需要代码复制按钮，请问应该怎么加上这个功能

**Comment by wenjy** [comment]
+1

**Comment by iamhaifeng** [comment]
我按照如下教程的方法实现了，效果不错，建议作者合并至master。@rujews

https://huangzhongde.cn/post/2020-02-21-hugo-code-copy-to-clipboard/

**Comment by rujews** [comment]
可以贡献个commit @iamhaifeng

**Comment by realchoi** [comment]
@rujews 你好，现在的代码块显示不够规整，行数越多，左侧的行号和代码块就错位得越厉害，请问可以修复一下吗？详情如下：
![](https://s3.bmp.ovh/imgs/2022/08/23/a4bf817c237927f6.png)

**请问能否做成本 issue 作者实现的效果？**

**Comment by realchoi** [comment]
> @rujews 你好，现在的代码块显示不够规整，行数越多，左侧的行号和代码块就错位得越厉害，请问可以修复一下吗？详情如下： ![](https://camo.githubusercontent.com/cbe91d7692d5529a93487ba782638fe412b6cd86302363013e8e537c775f2313/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30382f32332f613462663831376332333739323766362e706e67)
> 
> **请问能否做成本 issue 作者实现的效果？**

而且，目前的代码块在移动端打开的时候，如果一行代码过长，会出现横向滚动条，而不是自动换行。

**Comment by rujews** [comment]
提个PR @realchoi

**Comment by rujews** [comment]
> > @rujews 你好，现在的代码块显示不够规整，行数越多，左侧的行号和代码块就错位得越厉害，请问可以修复一下吗？详情如下： ![](https://camo.githubusercontent.com/cbe91d7692d5529a93487ba782638fe412b6cd86302363013e8e537c775f2313/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30382f32332f613462663831376332333739323766362e706e67)
> > **请问能否做成本 issue 作者实现的效果？**
> 
> 而且，目前的代码块在移动端打开的时候，如果一行代码过长，会出现横向滚动条，而不是自动换行。

已经修复了
