### ISSUE TITLE
代码显示还是不正常

### ISSUE THREAD

**Issue by lfishRhungry** [flysnow-org/maupassant-hugo#97]
hugo版本：0\.71\.0
文章内代码块显示如下：
![chrome_kOupO54AhL](https://user-images.githubusercontent.com/52651594/82752708-822f3600-9df2-11ea-8bd7-1619fa5b0306.png)

**Comment by rujews** [comment]
使用旧版本Hugo 0.61.0试试，可能是升级后的不兼容

**Comment by rujews** [comment]
经测试，新版0.72没有问题，看下自己的配置是否正确。
