### ISSUE TITLE
老大 这代码块的样子实在是有点接受不了啊

### ISSUE THREAD

**Issue by lfishRhungry** [flysnow-org/maupassant-hugo#99]
怎么说呢 也是能够阅读 但是形象不佳 希望老大有空时能改良一下：
![chrome_iZwbB7gmqZ](https://user-images.githubusercontent.com/52651594/83480905-15412d80-a4cf-11ea-82bd-5f4ef4fa82a2.png)

**Comment by rujews** [comment]
使用旧版本Hugo 0.61.0试试，可能是升级后的不兼容

**Comment by rujews** [comment]
经测试，新版0.72没有问题，看下自己的配置是否正确。
